// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8zg9HbMPIxt9nvTWaL8Mwn70HpcG4V9Q',
    appId: '1:1048089903277:web:5b6bd3fe0e3ef685368624',
    messagingSenderId: '1048089903277',
    projectId: 'to-do-list-59ba2',
    authDomain: 'to-do-list-59ba2.firebaseapp.com',
    storageBucket: 'to-do-list-59ba2.firebasestorage.app',
    measurementId: 'G-Y2J1JKDTR5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1sYrJJ9eZTu4WyM0lRGmW_GflSNOCCKQ',
    appId: '1:1048089903277:android:fed94ba857fb395e368624',
    messagingSenderId: '1048089903277',
    projectId: 'to-do-list-59ba2',
    storageBucket: 'to-do-list-59ba2.firebasestorage.app',
  );
}
